// <auto-generated />
namespace Football.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class create_addet_Cards_to_Players : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_addet_Cards_to_Players));
        
        string IMigrationMetadata.Id
        {
            get { return "202102170310055_create_addet_Cards_to_Players"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
